disabled_rules:
  - trailing_whitespace
line_length:
  warning: 140
  error: 200
identifier_name:
  min_length:
    warning: 2
function_body_length:
  warning: 60
  error: 100
excluded:
  - Pods
  - .build
  - "**/__Snapshots__"
